---
title: "Decision Trees and Random Forests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE )
knitr::opts_knit$set(root.dir = '../..')
```

Prior beginning, source all the required dependencies.

```{r load dependencies}
source('src/lib.R')
```

***
TODO: insert comment and insert random forest

***

## R Markdown

Get the data

```{r get dataframe}
df = get_partitioned_df()
```

```{r model info}
info = getModelInfo()
info %>% names %>% head
info %>% names %>% length
```


```{r dataset}
data_name = 'spirals'


get_full_dataset() %>% filter(type == data_name) %>% ggplot(aes(x = x, y = y, color = class)) +
  scale_fill_discrete() + geom_point(size = 2) + theme_bw() + ggtitle(data_name %>% toupper)
```

```{r hyperparameters}

algorithm = 'rpart2'

info[[algorithm]]$parameters

maxdepth = 1

hyperparameters = data.frame('maxdepth' = maxdepth)

```

```{r model fit 2}
model = train(y = df$spirals$y_train$class,
           x = df$spirals$x_train,
           method = algorithm,
           tuneGrid = hyperparameters,
           trControl = trainControl(method = 'boot')
           )
```

```{r model structure 2}
plot(model$finalModel, uniform=TRUE,margin=0.2)
text(model$finalModel, use.n=TRUE, all=TRUE, cex=0.8)
```


```{r plot 2,}
  ### prepare prediction

  from <- 0
  to <- 1
  n <- 100
  grid_df <- expand.grid(
    x = seq(from, to, length.out = n),
    y = seq(from, to, length.out = n)
  )
  
  grid_df$prob = model %>% predict(grid_df %>% select(x,y), type = 'prob') %>% select(prob = class_1)
  
  ## Prepare plot dataset
  
  data_df <- lapply(
    data_name,
    function(data_name) {
      df <- df[[data_name]] 
      rbind(
        df$full_train %>% mutate(partition = "train"),
        df$full_val %>% mutate(partition = "val")
      )
    }
  ) %>% bind_rows
  
  ## plot data
  ggplot() + 
    geom_raster(data = grid_df, aes(x = x, y = y, fill = prob), interpolate = T, alpha = 0.7) +
    scale_fill_gradient2(low = "blue", mid = "white",
                         high = "red", midpoint = 0.5, space = "rgb",
                         na.value = "grey50", guide = "colourbar") +
    geom_point(data = data_df, aes(x = x, y = y, fill = 1- (as.numeric(factor(class)) - 1), alpha = partition), shape = 21) +
    scale_alpha_manual(values = c("train" = 0.6, "test" = 1)) +
    theme_minimal() +
    theme(legend.position = "none")

```

## Tweak Hyperparameter
```{r}
maxdepth = seq_len(10)

hyperparameters = data.frame('maxdepth' = maxdepth)
```

```{r model fit}
model = train(y = df$spirals$y_train$class,
           x = df$spirals$x_train,
           method = algorithm,
           tuneGrid = hyperparameters,
           trControl = trainControl(method = 'boot')
           )
```

```{r}
plot(model)
```


```{r model structure, echo = FALSE}
plot(model$finalModel, uniform=TRUE,margin=0.2)
text(model$finalModel, use.n=TRUE, all=TRUE, cex=0.8)
```

```{r plot, echo=FALSE}
  ### prepare prediction

  from <- 0
  to <- 1
  n <- 100
  grid_df <- expand.grid(
    x = seq(from, to, length.out = n),
    y = seq(from, to, length.out = n)
  )
  
  grid_df$prob = model %>% predict(grid_df %>% select(x,y), type = 'prob') %>% select(prob = class_1)
  
  ## Prepare plot dataset
  
  data_df <- lapply(
    data_name,
    function(data_name) {
      df <- df[[data_name]] 
      rbind(
        df$full_train %>% mutate(partition = "train"),
        df$full_val %>% mutate(partition = "val")
      )
    }
  ) %>% bind_rows
  
  ## plot data
  ggplot() + 
    geom_raster(data = grid_df, aes(x = x, y = y, fill = prob), interpolate = T, alpha = 0.7) +
    scale_fill_gradient2(low = "blue", mid = "white",
                         high = "red", midpoint = 0.5, space = "rgb",
                         na.value = "grey50", guide = "colourbar") +
    geom_point(data = data_df, aes(x = x, y = y, fill = 1- (as.numeric(factor(class)) - 1), alpha = partition), shape = 21) +
    scale_alpha_manual(values = c("train" = 0.6, "test" = 1)) +
    theme_minimal() +
    theme(legend.position = "none")

```